apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
spec:
  conversion:
    strategy: None
  group: samplecontroller.k8s.io
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  preserveUnknownFields: true
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
